// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { ContractRequestData, ContractRequestResponses, CreateAgreementData, CreateAgreementResponses, CreateEventData, CreateEventResponses, GetNegotiationData, GetNegotiationResponses, InitialContractOfferData, InitialContractOfferResponses, InitialContractRequestData, InitialContractRequestResponses, ProviderOfferData, ProviderOfferResponses, TerminateNegotiationData, TerminateNegotiationResponses, VerifyAgreementData, VerifyAgreementResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DefaultService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DefaultService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DefaultService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DefaultService.__registry.set(this, args?.key);
    }
    
    public initialContractOffer<ThrowOnError extends boolean = false>(options?: Options<InitialContractOfferData, ThrowOnError>) {
        return (options?.client ?? this.client).post<InitialContractOfferResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/offer',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public initialContractRequest<ThrowOnError extends boolean = false>(options?: Options<InitialContractRequestData, ThrowOnError>) {
        return (options?.client ?? this.client).post<InitialContractRequestResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public getNegotiation<ThrowOnError extends boolean = false>(options: Options<GetNegotiationData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetNegotiationResponses, unknown, ThrowOnError>({ url: '/2024/1/negotiations/{id}', ...options });
    }
    
    public createAgreement<ThrowOnError extends boolean = false>(options: Options<CreateAgreementData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateAgreementResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/agreement',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public verifyAgreement<ThrowOnError extends boolean = false>(options: Options<VerifyAgreementData, ThrowOnError>) {
        return (options.client ?? this.client).post<VerifyAgreementResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/agreement/verification',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public createEvent<ThrowOnError extends boolean = false>(options: Options<CreateEventData, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateEventResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/events',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public providerOffer<ThrowOnError extends boolean = false>(options: Options<ProviderOfferData, ThrowOnError>) {
        return (options.client ?? this.client).post<ProviderOfferResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/offer',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public contractRequest<ThrowOnError extends boolean = false>(options: Options<ContractRequestData, ThrowOnError>) {
        return (options.client ?? this.client).post<ContractRequestResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public terminateNegotiation<ThrowOnError extends boolean = false>(options: Options<TerminateNegotiationData, ThrowOnError>) {
        return (options.client ?? this.client).post<TerminateNegotiationResponses, unknown, ThrowOnError>({
            url: '/2024/1/negotiations/{id}/termination',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
