// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type SecretOutput = {
    '@id'?: string;
    '@type'?: string;
    'https://w3id.org/edc/v0.0.1/ns/value': string;
};

export type VersionRecord = {
    lastUpdated?: string;
    maturity?: string;
    urlPath?: string;
    version?: string;
};

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/version';
};

export type GetVersionResponses = {
    /**
     * The secret
     */
    200: SecretOutput;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];
