// This file is auto-generated by @hey-api/openapi-ts

export { EdrCacheV3Service, type Options } from './sdk.gen.js';
export type { ApiErrorDetail, ClientOptions, Criterion, DataAddress, EndpointDataReferenceEntry, GetEdrEntryDataAddressV3Data, GetEdrEntryDataAddressV3Error, GetEdrEntryDataAddressV3Errors, GetEdrEntryDataAddressV3Response, GetEdrEntryDataAddressV3Responses, JsonArray, JsonObject, JsonValue, QuerySpec, RemoveEdrEntryV3Data, RemoveEdrEntryV3Error, RemoveEdrEntryV3Errors, RemoveEdrEntryV3Response, RemoveEdrEntryV3Responses, RequestEdrEntriesV3Data, RequestEdrEntriesV3Error, RequestEdrEntriesV3Errors, RequestEdrEntriesV3Response, RequestEdrEntriesV3Responses } from './types.gen.js';
