// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetEdrEntryDataAddressV3Data, GetEdrEntryDataAddressV3Errors, GetEdrEntryDataAddressV3Responses, RemoveEdrEntryV3Data, RemoveEdrEntryV3Errors, RemoveEdrEntryV3Responses, RequestEdrEntriesV3Data, RequestEdrEntriesV3Errors, RequestEdrEntriesV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new EdrCacheV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class EdrCacheV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<EdrCacheV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        EdrCacheV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Request all Edr entries according to a particular query
     */
    public requestEdrEntriesV3<ThrowOnError extends boolean = false>(options?: Options<RequestEdrEntriesV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<RequestEdrEntriesV3Responses, RequestEdrEntriesV3Errors, ThrowOnError>({
            url: '/v3/edrs/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Removes an EDR entry given the transfer process ID
     */
    public removeEdrEntryV3<ThrowOnError extends boolean = false>(options: Options<RemoveEdrEntryV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<RemoveEdrEntryV3Responses, RemoveEdrEntryV3Errors, ThrowOnError>({ url: '/v3/edrs/{transferProcessId}', ...options });
    }
    
    /**
     * Gets the EDR data address with the given transfer process ID
     */
    public getEdrEntryDataAddressV3<ThrowOnError extends boolean = false>(options: Options<GetEdrEntryDataAddressV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetEdrEntryDataAddressV3Responses, GetEdrEntryDataAddressV3Errors, ThrowOnError>({ url: '/v3/edrs/{transferProcessId}/dataaddress', ...options });
    }
}
