// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type DataAddress = {
    '@type'?: string;
    type?: string;
};

export type EndpointDataReferenceEntry = {
    '@id'?: string;
    '@type'?: string;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type RequestEdrEntriesV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/edrs/request';
};

export type RequestEdrEntriesV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type RequestEdrEntriesV3Error = RequestEdrEntriesV3Errors[keyof RequestEdrEntriesV3Errors];

export type RequestEdrEntriesV3Responses = {
    /**
     * The edr entries matching the query
     */
    200: Array<EndpointDataReferenceEntry>;
};

export type RequestEdrEntriesV3Response = RequestEdrEntriesV3Responses[keyof RequestEdrEntriesV3Responses];

export type RemoveEdrEntryV3Data = {
    body?: never;
    path: {
        transferProcessId: string;
    };
    query?: never;
    url: '/v3/edrs/{transferProcessId}';
};

export type RemoveEdrEntryV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An EDR entry with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type RemoveEdrEntryV3Error = RemoveEdrEntryV3Errors[keyof RemoveEdrEntryV3Errors];

export type RemoveEdrEntryV3Responses = {
    /**
     * EDR entry was deleted successfully
     */
    204: void;
};

export type RemoveEdrEntryV3Response = RemoveEdrEntryV3Responses[keyof RemoveEdrEntryV3Responses];

export type GetEdrEntryDataAddressV3Data = {
    body?: never;
    path: {
        transferProcessId: string;
    };
    query?: never;
    url: '/v3/edrs/{transferProcessId}/dataaddress';
};

export type GetEdrEntryDataAddressV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An EDR data address with the given transfer process ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetEdrEntryDataAddressV3Error = GetEdrEntryDataAddressV3Errors[keyof GetEdrEntryDataAddressV3Errors];

export type GetEdrEntryDataAddressV3Responses = {
    /**
     * The data address
     */
    200: DataAddress;
};

export type GetEdrEntryDataAddressV3Response = GetEdrEntryDataAddressV3Responses[keyof GetEdrEntryDataAddressV3Responses];
