// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: {
        [key: string]: unknown;
    };
    message?: string;
    path?: string;
    type?: string;
};

export type DataAddress = {
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type TransferProcessFailStateDto = {
    errorMessage?: string;
};

export type CompleteData = {
    body?: never;
    path: {
        processId: string;
    };
    query?: never;
    url: '/transferprocess/{processId}/complete';
};

export type CompleteErrors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
};

export type CompleteError = CompleteErrors[keyof CompleteErrors];

export type FailData = {
    body?: TransferProcessFailStateDto;
    path: {
        processId: string;
    };
    query?: never;
    url: '/transferprocess/{processId}/fail';
};

export type FailErrors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
};

export type FailError = FailErrors[keyof FailErrors];

export type ProvisionedData = {
    body?: DataAddress;
    path: {
        processId: string;
    };
    query?: never;
    url: '/transferprocess/{processId}/provisioned';
};

export type ProvisionedErrors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
};

export type ProvisionedError = ProvisionedErrors[keyof ProvisionedErrors];
