// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetAgreementByIdV3Data, GetAgreementByIdV3Errors, GetAgreementByIdV3Responses, GetAgreementByIdV4AlphaData, GetAgreementByIdV4AlphaErrors, GetAgreementByIdV4AlphaResponses, GetNegotiationByAgreementIdV3Data, GetNegotiationByAgreementIdV3Errors, GetNegotiationByAgreementIdV3Responses, GetNegotiationByAgreementIdV4AlphaData, GetNegotiationByAgreementIdV4AlphaErrors, GetNegotiationByAgreementIdV4AlphaResponses, QueryAgreementsV3Data, QueryAgreementsV3Errors, QueryAgreementsV3Responses, QueryAgreementsV4AlphaData, QueryAgreementsV4AlphaErrors, QueryAgreementsV4AlphaResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ContractAgreementV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

class HeyApiClient2 {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry2<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ContractAgreementV4AlphaService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ContractAgreementV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<ContractAgreementV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ContractAgreementV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Gets all contract agreements according to a particular query
     */
    public queryAgreementsV3<ThrowOnError extends boolean = false>(options?: Options<QueryAgreementsV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryAgreementsV3Responses, QueryAgreementsV3Errors, ThrowOnError>({
            url: '/v3/contractagreements/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Gets an contract agreement with the given ID
     */
    public getAgreementByIdV3<ThrowOnError extends boolean = false>(options: Options<GetAgreementByIdV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetAgreementByIdV3Responses, GetAgreementByIdV3Errors, ThrowOnError>({ url: '/v3/contractagreements/{id}', ...options });
    }
    
    /**
     * Gets a contract negotiation with the given contract agreement ID
     */
    public getNegotiationByAgreementIdV3<ThrowOnError extends boolean = false>(options: Options<GetNegotiationByAgreementIdV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetNegotiationByAgreementIdV3Responses, GetNegotiationByAgreementIdV3Errors, ThrowOnError>({ url: '/v3/contractagreements/{id}/negotiation', ...options });
    }
}

export class ContractAgreementV4AlphaService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry2<ContractAgreementV4AlphaService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ContractAgreementV4AlphaService.__registry.set(this, args?.key);
    }
    
    /**
     * Gets all contract agreements according to a particular query
     */
    public queryAgreementsV4Alpha<ThrowOnError extends boolean = false>(options?: Options<QueryAgreementsV4AlphaData, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryAgreementsV4AlphaResponses, QueryAgreementsV4AlphaErrors, ThrowOnError>({
            url: '/v4alpha/contractagreements/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Gets an contract agreement with the given ID
     */
    public getAgreementByIdV4Alpha<ThrowOnError extends boolean = false>(options: Options<GetAgreementByIdV4AlphaData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetAgreementByIdV4AlphaResponses, GetAgreementByIdV4AlphaErrors, ThrowOnError>({ url: '/v4alpha/contractagreements/{id}', ...options });
    }
    
    /**
     * Gets a contract negotiation with the given contract agreement ID
     */
    public getNegotiationByAgreementIdV4Alpha<ThrowOnError extends boolean = false>(options: Options<GetNegotiationByAgreementIdV4AlphaData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetNegotiationByAgreementIdV4AlphaResponses, GetNegotiationByAgreementIdV4AlphaErrors, ThrowOnError>({ url: '/v4alpha/contractagreements/{id}/negotiation', ...options });
    }
}
