// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type CallbackAddress = {
    '@type'?: string;
    authCodeId?: string;
    authKey?: string;
    events?: Array<string>;
    transactional?: boolean;
    uri?: string;
};

export type ContractAgreement = {
    '@id'?: string;
    '@type'?: string;
    assetId?: string;
    consumerId?: string;
    contractSigningDate?: number;
    policy?: Policy;
    providerId?: string;
};

export type ContractNegotiation = {
    '@id'?: string;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractAgreementId?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    errorDetail?: string;
    protocol?: string;
    state?: string;
    type?: 'CONSUMER' | 'PROVIDER';
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

/**
 * ODRL policy
 */
export type Policy = {
    [key: string]: unknown;
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type QueryAgreementsV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/contractagreements/request';
};

export type QueryAgreementsV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryAgreementsV3Error = QueryAgreementsV3Errors[keyof QueryAgreementsV3Errors];

export type QueryAgreementsV3Responses = {
    /**
     * The contract agreements matching the query
     */
    200: Array<ContractAgreement>;
};

export type QueryAgreementsV3Response = QueryAgreementsV3Responses[keyof QueryAgreementsV3Responses];

export type GetAgreementByIdV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractagreements/{id}';
};

export type GetAgreementByIdV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract agreement with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetAgreementByIdV3Error = GetAgreementByIdV3Errors[keyof GetAgreementByIdV3Errors];

export type GetAgreementByIdV3Responses = {
    /**
     * The contract agreement
     */
    200: ContractAgreement;
};

export type GetAgreementByIdV3Response = GetAgreementByIdV3Responses[keyof GetAgreementByIdV3Responses];

export type GetNegotiationByAgreementIdV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractagreements/{id}/negotiation';
};

export type GetNegotiationByAgreementIdV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract agreement with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetNegotiationByAgreementIdV3Error = GetNegotiationByAgreementIdV3Errors[keyof GetNegotiationByAgreementIdV3Errors];

export type GetNegotiationByAgreementIdV3Responses = {
    /**
     * The contract negotiation
     */
    200: ContractNegotiation;
};

export type GetNegotiationByAgreementIdV3Response = GetNegotiationByAgreementIdV3Responses[keyof GetNegotiationByAgreementIdV3Responses];

export type QueryAgreementsV4AlphaData = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v4alpha/contractagreements/request';
};

export type QueryAgreementsV4AlphaErrors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryAgreementsV4AlphaError = QueryAgreementsV4AlphaErrors[keyof QueryAgreementsV4AlphaErrors];

export type QueryAgreementsV4AlphaResponses = {
    /**
     * The contract agreements matching the query
     */
    200: Array<ContractAgreement>;
};

export type QueryAgreementsV4AlphaResponse = QueryAgreementsV4AlphaResponses[keyof QueryAgreementsV4AlphaResponses];

export type GetAgreementByIdV4AlphaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v4alpha/contractagreements/{id}';
};

export type GetAgreementByIdV4AlphaErrors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract agreement with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetAgreementByIdV4AlphaError = GetAgreementByIdV4AlphaErrors[keyof GetAgreementByIdV4AlphaErrors];

export type GetAgreementByIdV4AlphaResponses = {
    /**
     * The contract agreement
     */
    200: ContractAgreement;
};

export type GetAgreementByIdV4AlphaResponse = GetAgreementByIdV4AlphaResponses[keyof GetAgreementByIdV4AlphaResponses];

export type GetNegotiationByAgreementIdV4AlphaData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v4alpha/contractagreements/{id}/negotiation';
};

export type GetNegotiationByAgreementIdV4AlphaErrors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract agreement with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetNegotiationByAgreementIdV4AlphaError = GetNegotiationByAgreementIdV4AlphaErrors[keyof GetNegotiationByAgreementIdV4AlphaErrors];

export type GetNegotiationByAgreementIdV4AlphaResponses = {
    /**
     * The contract negotiation
     */
    200: ContractNegotiation;
};

export type GetNegotiationByAgreementIdV4AlphaResponse = GetNegotiationByAgreementIdV4AlphaResponses[keyof GetNegotiationByAgreementIdV4AlphaResponses];
