// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetDatasetV3Data, GetDatasetV3Responses, RequestCatalogV3Data, RequestCatalogV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new CatalogV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class CatalogV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<CatalogV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        CatalogV3Service.__registry.set(this, args?.key);
    }
    
    public getDatasetV3<ThrowOnError extends boolean = false>(options?: Options<GetDatasetV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<GetDatasetV3Responses, unknown, ThrowOnError>({
            url: '/v3/catalog/dataset/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public requestCatalogV3<ThrowOnError extends boolean = false>(options?: Options<RequestCatalogV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<RequestCatalogV3Responses, unknown, ThrowOnError>({
            url: '/v3/catalog/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
