// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

/**
 * DCAT catalog
 */
export type Catalog = {
    [key: string]: unknown;
};

export type CatalogRequest = {
    '@context': {
        [key: string]: unknown;
    };
    '@type'?: string;
    additionalScopes?: Array<string>;
    counterPartyAddress: string;
    counterPartyId?: string;
    protocol: string;
    querySpec?: QuerySpec;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

/**
 * DCAT dataset
 */
export type Dataset = {
    [key: string]: unknown;
};

export type DatasetRequest = {
    '@type'?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    protocol?: string;
    querySpec?: QuerySpec;
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type GetDatasetV3Data = {
    body?: DatasetRequest;
    path?: never;
    query?: never;
    url: '/v3/catalog/dataset/request';
};

export type GetDatasetV3Responses = {
    /**
     * Gets single dataset from a connector
     */
    default: Dataset;
};

export type GetDatasetV3Response = GetDatasetV3Responses[keyof GetDatasetV3Responses];

export type RequestCatalogV3Data = {
    body?: CatalogRequest;
    path?: never;
    query?: never;
    url: '/v3/catalog/request';
};

export type RequestCatalogV3Responses = {
    /**
     * Gets contract offers (=catalog) of a single connector
     */
    default: Catalog;
};

export type RequestCatalogV3Response = RequestCatalogV3Responses[keyof RequestCatalogV3Responses];
