// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeleteDataplaneData, DeleteDataplaneErrors, DeleteDataplaneResponses, FindDataPlaneByIdData, FindDataPlaneByIdErrors, FindDataPlaneByIdResponses, GetAllDataPlaneInstancesData, GetAllDataPlaneInstancesResponses, RegisterDataplaneData, RegisterDataplaneErrors, RegisterDataplaneResponses, UnregisterDataplaneData, UnregisterDataplaneErrors, UnregisterDataplaneResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DataplaneSelectorService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DataplaneSelectorService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DataplaneSelectorService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DataplaneSelectorService.__registry.set(this, args?.key);
    }
    
    /**
     * Returns a list of all currently registered data plane instances
     */
    public getAllDataPlaneInstances<ThrowOnError extends boolean = false>(options?: Options<GetAllDataPlaneInstancesData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetAllDataPlaneInstancesResponses, unknown, ThrowOnError>({ url: '/v1/dataplanes', ...options });
    }
    
    /**
     * Register new Dataplane
     */
    public registerDataplane<ThrowOnError extends boolean = false>(options?: Options<RegisterDataplaneData, ThrowOnError>) {
        return (options?.client ?? this.client).post<RegisterDataplaneResponses, RegisterDataplaneErrors, ThrowOnError>({
            url: '/v1/dataplanes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete existing Dataplane
     */
    public deleteDataplane<ThrowOnError extends boolean = false>(options: Options<DeleteDataplaneData, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteDataplaneResponses, DeleteDataplaneErrors, ThrowOnError>({ url: '/v1/dataplanes/{id}', ...options });
    }
    
    /**
     * Returns the Data Plane Instance with the specified id.
     */
    public findDataPlaneById<ThrowOnError extends boolean = false>(options: Options<FindDataPlaneByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<FindDataPlaneByIdResponses, FindDataPlaneByIdErrors, ThrowOnError>({ url: '/v1/dataplanes/{id}', ...options });
    }
    
    /**
     * Unregister existing Dataplane
     */
    public unregisterDataplane<ThrowOnError extends boolean = false>(options: Options<UnregisterDataplaneData, ThrowOnError>) {
        return (options.client ?? this.client).put<UnregisterDataplaneResponses, UnregisterDataplaneErrors, ThrowOnError>({ url: '/v1/dataplanes/{id}/unregister', ...options });
    }
}
