// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type DataPlaneInstanceSchema = {
    '@context': {
        [key: string]: unknown;
    };
    '@id': string;
    '@type'?: string;
    allowedDestTypes: Array<string>;
    allowedSourceTypes: Array<string>;
    url: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type GetAllDataPlaneInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/dataplanes';
};

export type GetAllDataPlaneInstancesResponses = {
    /**
     * A (potentially empty) list of currently registered data plane instances
     */
    200: Array<DataPlaneInstanceSchema>;
};

export type GetAllDataPlaneInstancesResponse = GetAllDataPlaneInstancesResponses[keyof GetAllDataPlaneInstancesResponses];

export type RegisterDataplaneData = {
    body?: DataPlaneInstanceSchema;
    path?: never;
    query?: never;
    url: '/v1/dataplanes';
};

export type RegisterDataplaneErrors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Resource already exists
     */
    409: Array<ApiErrorDetail>;
};

export type RegisterDataplaneError = RegisterDataplaneErrors[keyof RegisterDataplaneErrors];

export type RegisterDataplaneResponses = {
    /**
     * Dataplane successfully registered
     */
    200: IdResponse;
};

export type RegisterDataplaneResponse = RegisterDataplaneResponses[keyof RegisterDataplaneResponses];

export type DeleteDataplaneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/dataplanes/{id}';
};

export type DeleteDataplaneErrors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Resource not found
     */
    404: Array<ApiErrorDetail>;
    /**
     * Conflict
     */
    409: Array<ApiErrorDetail>;
};

export type DeleteDataplaneError = DeleteDataplaneErrors[keyof DeleteDataplaneErrors];

export type DeleteDataplaneResponses = {
    /**
     * Dataplane successfully deleted
     */
    204: void;
};

export type DeleteDataplaneResponse = DeleteDataplaneResponses[keyof DeleteDataplaneResponses];

export type FindDataPlaneByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/dataplanes/{id}';
};

export type FindDataPlaneByIdErrors = {
    /**
     * Resource not found
     */
    404: Array<ApiErrorDetail>;
};

export type FindDataPlaneByIdError = FindDataPlaneByIdErrors[keyof FindDataPlaneByIdErrors];

export type FindDataPlaneByIdResponses = {
    /**
     * The Data Plane Instance
     */
    200: DataPlaneInstanceSchema;
};

export type FindDataPlaneByIdResponse = FindDataPlaneByIdResponses[keyof FindDataPlaneByIdResponses];

export type UnregisterDataplaneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/dataplanes/{id}/unregister';
};

export type UnregisterDataplaneErrors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Resource not found
     */
    404: Array<ApiErrorDetail>;
    /**
     * Conflict
     */
    409: Array<ApiErrorDetail>;
};

export type UnregisterDataplaneError = UnregisterDataplaneErrors[keyof UnregisterDataplaneErrors];

export type UnregisterDataplaneResponses = {
    /**
     * Dataplane successfully unregistered
     */
    204: void;
};

export type UnregisterDataplaneResponse = UnregisterDataplaneResponses[keyof UnregisterDataplaneResponses];
