// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeprovisionTransferProcessV3Data, DeprovisionTransferProcessV3Errors, DeprovisionTransferProcessV3Responses, GetTransferProcessStateV3Data, GetTransferProcessStateV3Errors, GetTransferProcessStateV3Responses, GetTransferProcessV3Data, GetTransferProcessV3Errors, GetTransferProcessV3Responses, InitiateTransferProcessV3Data, InitiateTransferProcessV3Errors, InitiateTransferProcessV3Responses, QueryTransferProcessesV3Data, QueryTransferProcessesV3Errors, QueryTransferProcessesV3Responses, ResumeTransferProcessV3Data, ResumeTransferProcessV3Errors, ResumeTransferProcessV3Responses, SuspendTransferProcessV3Data, SuspendTransferProcessV3Errors, SuspendTransferProcessV3Responses, TerminateTransferProcessV3Data, TerminateTransferProcessV3Errors, TerminateTransferProcessV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new TransferProcessV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class TransferProcessV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<TransferProcessV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        TransferProcessV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Initiates a data transfer with the given parameters. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
     */
    public initiateTransferProcessV3<ThrowOnError extends boolean = false>(options?: Options<InitiateTransferProcessV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<InitiateTransferProcessV3Responses, InitiateTransferProcessV3Errors, ThrowOnError>({
            url: '/v3/transferprocesses',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Returns all transfer process according to a query
     */
    public queryTransferProcessesV3<ThrowOnError extends boolean = false>(options?: Options<QueryTransferProcessesV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryTransferProcessesV3Responses, QueryTransferProcessesV3Errors, ThrowOnError>({
            url: '/v3/transferprocesses/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Gets an transfer process with the given ID
     */
    public getTransferProcessV3<ThrowOnError extends boolean = false>(options: Options<GetTransferProcessV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetTransferProcessV3Responses, GetTransferProcessV3Errors, ThrowOnError>({ url: '/v3/transferprocesses/{id}', ...options });
    }
    
    /**
     * Requests the deprovisioning of resources associated with a transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
     */
    public deprovisionTransferProcessV3<ThrowOnError extends boolean = false>(options: Options<DeprovisionTransferProcessV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<DeprovisionTransferProcessV3Responses, DeprovisionTransferProcessV3Errors, ThrowOnError>({ url: '/v3/transferprocesses/{id}/deprovision', ...options });
    }
    
    /**
     * Requests the resumption of a suspended transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
     */
    public resumeTransferProcessV3<ThrowOnError extends boolean = false>(options: Options<ResumeTransferProcessV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<ResumeTransferProcessV3Responses, ResumeTransferProcessV3Errors, ThrowOnError>({ url: '/v3/transferprocesses/{id}/resume', ...options });
    }
    
    /**
     * Gets the state of a transfer process with the given ID
     */
    public getTransferProcessStateV3<ThrowOnError extends boolean = false>(options: Options<GetTransferProcessStateV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetTransferProcessStateV3Responses, GetTransferProcessStateV3Errors, ThrowOnError>({ url: '/v3/transferprocesses/{id}/state', ...options });
    }
    
    /**
     * Requests the suspension of a transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
     */
    public suspendTransferProcessV3<ThrowOnError extends boolean = false>(options: Options<SuspendTransferProcessV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<SuspendTransferProcessV3Responses, SuspendTransferProcessV3Errors, ThrowOnError>({
            url: '/v3/transferprocesses/{id}/suspend',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Requests the termination of a transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
     */
    public terminateTransferProcessV3<ThrowOnError extends boolean = false>(options: Options<TerminateTransferProcessV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<TerminateTransferProcessV3Responses, TerminateTransferProcessV3Errors, ThrowOnError>({
            url: '/v3/transferprocesses/{id}/terminate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
