// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type CallbackAddress = {
    '@type'?: string;
    authCodeId?: string;
    authKey?: string;
    events?: Array<string>;
    transactional?: boolean;
    uri?: string;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type DataAddress = {
    '@type'?: string;
    type?: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type Properties = {
    [key: string]: unknown;
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type SuspendTransfer = {
    '@type'?: string;
    state?: string;
};

export type TerminateTransfer = {
    '@type'?: string;
    state?: string;
};

export type TransferProcess = {
    '@id'?: string;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractAgreementId?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    dataDestination?: DataAddress;
    errorDetail?: string;
    privateProperties?: Properties;
    protocol?: string;
    state?: string;
    type?: 'CONSUMER' | 'PROVIDER';
};

export type TransferRequest = {
    '@context': {
        [key: string]: unknown;
    };
    '@type'?: string;
    /**
     * @deprecated
     */
    assetId?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractId: string;
    counterPartyAddress: string;
    dataDestination?: DataAddress;
    privateProperties?: Properties;
    protocol: string;
    transferType: string;
};

export type TransferState = {
    '@type'?: string;
    state?: string;
};

export type InitiateTransferProcessV3Data = {
    body?: TransferRequest;
    path?: never;
    query?: never;
    url: '/v3/transferprocesses';
};

export type InitiateTransferProcessV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type InitiateTransferProcessV3Error = InitiateTransferProcessV3Errors[keyof InitiateTransferProcessV3Errors];

export type InitiateTransferProcessV3Responses = {
    /**
     * The transfer was successfully initiated. Returns the transfer process ID and created timestamp
     */
    200: IdResponse;
};

export type InitiateTransferProcessV3Response = InitiateTransferProcessV3Responses[keyof InitiateTransferProcessV3Responses];

export type QueryTransferProcessesV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/transferprocesses/request';
};

export type QueryTransferProcessesV3Errors = {
    /**
     * Request was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryTransferProcessesV3Error = QueryTransferProcessesV3Errors[keyof QueryTransferProcessesV3Errors];

export type QueryTransferProcessesV3Responses = {
    /**
     * The transfer processes matching the query
     */
    200: Array<TransferProcess>;
};

export type QueryTransferProcessesV3Response = QueryTransferProcessesV3Responses[keyof QueryTransferProcessesV3Responses];

export type GetTransferProcessV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}';
};

export type GetTransferProcessV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetTransferProcessV3Error = GetTransferProcessV3Errors[keyof GetTransferProcessV3Errors];

export type GetTransferProcessV3Responses = {
    /**
     * The transfer process
     */
    200: TransferProcess;
};

export type GetTransferProcessV3Response = GetTransferProcessV3Responses[keyof GetTransferProcessV3Responses];

export type DeprovisionTransferProcessV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}/deprovision';
};

export type DeprovisionTransferProcessV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type DeprovisionTransferProcessV3Error = DeprovisionTransferProcessV3Errors[keyof DeprovisionTransferProcessV3Errors];

export type DeprovisionTransferProcessV3Responses = {
    /**
     * Request to deprovision the transfer process was successfully received
     */
    204: void;
};

export type DeprovisionTransferProcessV3Response = DeprovisionTransferProcessV3Responses[keyof DeprovisionTransferProcessV3Responses];

export type ResumeTransferProcessV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}/resume';
};

export type ResumeTransferProcessV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type ResumeTransferProcessV3Error = ResumeTransferProcessV3Errors[keyof ResumeTransferProcessV3Errors];

export type ResumeTransferProcessV3Responses = {
    /**
     * Request to resume the transfer process was successfully received
     */
    204: void;
};

export type ResumeTransferProcessV3Response = ResumeTransferProcessV3Responses[keyof ResumeTransferProcessV3Responses];

export type GetTransferProcessStateV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}/state';
};

export type GetTransferProcessStateV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An  transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetTransferProcessStateV3Error = GetTransferProcessStateV3Errors[keyof GetTransferProcessStateV3Errors];

export type GetTransferProcessStateV3Responses = {
    /**
     * The  transfer process's state
     */
    200: TransferState;
};

export type GetTransferProcessStateV3Response = GetTransferProcessStateV3Responses[keyof GetTransferProcessStateV3Responses];

export type SuspendTransferProcessV3Data = {
    body?: SuspendTransfer;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}/suspend';
};

export type SuspendTransferProcessV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
    /**
     * Could not suspend the transfer process, because it is already completed or terminated.
     */
    409: Array<ApiErrorDetail>;
};

export type SuspendTransferProcessV3Error = SuspendTransferProcessV3Errors[keyof SuspendTransferProcessV3Errors];

export type SuspendTransferProcessV3Responses = {
    /**
     * Request to suspend the transfer process was successfully received
     */
    204: void;
};

export type SuspendTransferProcessV3Response = SuspendTransferProcessV3Responses[keyof SuspendTransferProcessV3Responses];

export type TerminateTransferProcessV3Data = {
    body?: TerminateTransfer;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/transferprocesses/{id}/terminate';
};

export type TerminateTransferProcessV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A transfer process with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
    /**
     * Could not terminate transfer process, because it is already completed or terminated.
     */
    409: Array<ApiErrorDetail>;
};

export type TerminateTransferProcessV3Error = TerminateTransferProcessV3Errors[keyof TerminateTransferProcessV3Errors];

export type TerminateTransferProcessV3Responses = {
    /**
     * Request to terminate the transfer process was successfully received
     */
    204: void;
};

export type TerminateTransferProcessV3Response = TerminateTransferProcessV3Responses[keyof TerminateTransferProcessV3Responses];
