// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateExecutionPlaneV3Data, CreateExecutionPlaneV3Errors, CreateExecutionPlaneV3Responses, CreatePolicyDefinitionV3Data, CreatePolicyDefinitionV3Errors, CreatePolicyDefinitionV3Responses, DeletePolicyDefinitionV3Data, DeletePolicyDefinitionV3Errors, DeletePolicyDefinitionV3Responses, GetPolicyDefinitionV3Data, GetPolicyDefinitionV3Errors, GetPolicyDefinitionV3Responses, QueryPolicyDefinitionsV3Data, QueryPolicyDefinitionsV3Errors, QueryPolicyDefinitionsV3Responses, UpdatePolicyDefinitionV3Data, UpdatePolicyDefinitionV3Errors, UpdatePolicyDefinitionV3Responses, ValidatePolicyDefinitionV3Data, ValidatePolicyDefinitionV3Errors, ValidatePolicyDefinitionV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new PolicyDefinitionV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class PolicyDefinitionV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<PolicyDefinitionV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        PolicyDefinitionV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Creates a new policy definition
     */
    public createPolicyDefinitionV3<ThrowOnError extends boolean = false>(options?: Options<CreatePolicyDefinitionV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<CreatePolicyDefinitionV3Responses, CreatePolicyDefinitionV3Errors, ThrowOnError>({
            url: '/v3/policydefinitions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Returns all policy definitions according to a query
     */
    public queryPolicyDefinitionsV3<ThrowOnError extends boolean = false>(options?: Options<QueryPolicyDefinitionsV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryPolicyDefinitionsV3Responses, QueryPolicyDefinitionsV3Errors, ThrowOnError>({
            url: '/v3/policydefinitions/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Removes a policy definition with the given ID if possible. Deleting a policy definition is only possible if that policy definition is not yet referenced by a contract definition, in which case an error is returned. DANGER ZONE: Note that deleting policy definitions can have unexpected results, do this at your own risk!
     */
    public deletePolicyDefinitionV3<ThrowOnError extends boolean = false>(options: Options<DeletePolicyDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeletePolicyDefinitionV3Responses, DeletePolicyDefinitionV3Errors, ThrowOnError>({ url: '/v3/policydefinitions/{id}', ...options });
    }
    
    /**
     * Gets a policy definition with the given ID
     */
    public getPolicyDefinitionV3<ThrowOnError extends boolean = false>(options: Options<GetPolicyDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetPolicyDefinitionV3Responses, GetPolicyDefinitionV3Errors, ThrowOnError>({ url: '/v3/policydefinitions/{id}', ...options });
    }
    
    /**
     * Updates an existing Policy, If the Policy is not found, an error is reported
     */
    public updatePolicyDefinitionV3<ThrowOnError extends boolean = false>(options: Options<UpdatePolicyDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).put<UpdatePolicyDefinitionV3Responses, UpdatePolicyDefinitionV3Errors, ThrowOnError>({
            url: '/v3/policydefinitions/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Creates an execution plane for an existing Policy, If the Policy is not found, an error is reported
     */
    public createExecutionPlaneV3<ThrowOnError extends boolean = false>(options: Options<CreateExecutionPlaneV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<CreateExecutionPlaneV3Responses, CreateExecutionPlaneV3Errors, ThrowOnError>({
            url: '/v3/policydefinitions/{id}/evaluationplan',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Validates an existing Policy, If the Policy is not found, an error is reported
     */
    public validatePolicyDefinitionV3<ThrowOnError extends boolean = false>(options: Options<ValidatePolicyDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<ValidatePolicyDefinitionV3Responses, ValidatePolicyDefinitionV3Errors, ThrowOnError>({ url: '/v3/policydefinitions/{id}/validate', ...options });
    }
}
