// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

/**
 * ODRL policy
 */
export type Policy = {
    [key: string]: unknown;
};

export type PolicyDefinitionInput = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    policy: Policy;
};

export type PolicyDefinitionOutput = {
    '@id'?: string;
    '@type'?: string;
    policy?: Policy;
};

export type PolicyEvaluationPlanRequestSchema = {
    policyScope?: string;
};

export type PolicyEvaluationPlanSchema = {
    [key: string]: unknown;
};

export type PolicyValidationResultSchema = {
    errors?: Array<string>;
    isValid?: boolean;
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type CreatePolicyDefinitionV3Data = {
    body?: PolicyDefinitionInput;
    path?: never;
    query?: never;
    url: '/v3/policydefinitions';
};

export type CreatePolicyDefinitionV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Could not create policy definition, because a contract definition with that ID already exists
     */
    409: Array<ApiErrorDetail>;
};

export type CreatePolicyDefinitionV3Error = CreatePolicyDefinitionV3Errors[keyof CreatePolicyDefinitionV3Errors];

export type CreatePolicyDefinitionV3Responses = {
    /**
     * policy definition was created successfully. Returns the Policy Definition Id and created timestamp
     */
    200: IdResponse;
};

export type CreatePolicyDefinitionV3Response = CreatePolicyDefinitionV3Responses[keyof CreatePolicyDefinitionV3Responses];

export type QueryPolicyDefinitionsV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/policydefinitions/request';
};

export type QueryPolicyDefinitionsV3Errors = {
    /**
     * Request was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryPolicyDefinitionsV3Error = QueryPolicyDefinitionsV3Errors[keyof QueryPolicyDefinitionsV3Errors];

export type QueryPolicyDefinitionsV3Responses = {
    /**
     * The policy definitions matching the query
     */
    200: Array<PolicyDefinitionOutput>;
};

export type QueryPolicyDefinitionsV3Response = QueryPolicyDefinitionsV3Responses[keyof QueryPolicyDefinitionsV3Responses];

export type DeletePolicyDefinitionV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/policydefinitions/{id}';
};

export type DeletePolicyDefinitionV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An policy definition with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
    /**
     * The policy definition cannot be deleted, because it is referenced by a contract definition
     */
    409: Array<ApiErrorDetail>;
};

export type DeletePolicyDefinitionV3Error = DeletePolicyDefinitionV3Errors[keyof DeletePolicyDefinitionV3Errors];

export type DeletePolicyDefinitionV3Responses = {
    /**
     * Policy definition was deleted successfully
     */
    204: void;
};

export type DeletePolicyDefinitionV3Response = DeletePolicyDefinitionV3Responses[keyof DeletePolicyDefinitionV3Responses];

export type GetPolicyDefinitionV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/policydefinitions/{id}';
};

export type GetPolicyDefinitionV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An  policy definition with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetPolicyDefinitionV3Error = GetPolicyDefinitionV3Errors[keyof GetPolicyDefinitionV3Errors];

export type GetPolicyDefinitionV3Responses = {
    /**
     * The  policy definition
     */
    200: PolicyDefinitionOutput;
};

export type GetPolicyDefinitionV3Response = GetPolicyDefinitionV3Responses[keyof GetPolicyDefinitionV3Responses];

export type UpdatePolicyDefinitionV3Data = {
    body?: PolicyDefinitionInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/policydefinitions/{id}';
};

export type UpdatePolicyDefinitionV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * policy definition could not be updated, because it does not exists
     */
    404: ApiErrorDetail;
};

export type UpdatePolicyDefinitionV3Error = UpdatePolicyDefinitionV3Errors[keyof UpdatePolicyDefinitionV3Errors];

export type UpdatePolicyDefinitionV3Responses = {
    /**
     * policy definition was updated successfully.
     */
    204: void;
};

export type UpdatePolicyDefinitionV3Response = UpdatePolicyDefinitionV3Responses[keyof UpdatePolicyDefinitionV3Responses];

export type CreateExecutionPlaneV3Data = {
    body?: PolicyEvaluationPlanRequestSchema;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/policydefinitions/{id}/evaluationplan';
};

export type CreateExecutionPlaneV3Errors = {
    /**
     * An evaluation plan could not be created, because the policy definition does not exists
     */
    404: ApiErrorDetail;
};

export type CreateExecutionPlaneV3Error = CreateExecutionPlaneV3Errors[keyof CreateExecutionPlaneV3Errors];

export type CreateExecutionPlaneV3Responses = {
    /**
     * Returns the evaluation plan
     */
    200: PolicyEvaluationPlanSchema;
};

export type CreateExecutionPlaneV3Response = CreateExecutionPlaneV3Responses[keyof CreateExecutionPlaneV3Responses];

export type ValidatePolicyDefinitionV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/policydefinitions/{id}/validate';
};

export type ValidatePolicyDefinitionV3Errors = {
    /**
     * policy definition could not be validated, because it does not exists
     */
    404: ApiErrorDetail;
};

export type ValidatePolicyDefinitionV3Error = ValidatePolicyDefinitionV3Errors[keyof ValidatePolicyDefinitionV3Errors];

export type ValidatePolicyDefinitionV3Responses = {
    /**
     * Returns the validation result
     */
    200: PolicyValidationResultSchema;
};

export type ValidatePolicyDefinitionV3Response = ValidatePolicyDefinitionV3Responses[keyof ValidatePolicyDefinitionV3Responses];
