// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetAllDataPlaneInstancesV3Data, GetAllDataPlaneInstancesV3Responses, GetAllDataPlaneInstancesV4Data, GetAllDataPlaneInstancesV4Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DataplaneSelectorV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

class HeyApiClient2 {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry2<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DataplaneSelectorV4AlphaService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DataplaneSelectorV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DataplaneSelectorV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DataplaneSelectorV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Returns a list of all currently registered data plane instances
     */
    public getAllDataPlaneInstancesV3<ThrowOnError extends boolean = false>(options?: Options<GetAllDataPlaneInstancesV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetAllDataPlaneInstancesV3Responses, unknown, ThrowOnError>({ url: '/v3/dataplanes', ...options });
    }
}

export class DataplaneSelectorV4AlphaService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry2<DataplaneSelectorV4AlphaService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DataplaneSelectorV4AlphaService.__registry.set(this, args?.key);
    }
    
    /**
     * Returns a list of all currently registered data plane instances
     */
    public getAllDataPlaneInstancesV4<ThrowOnError extends boolean = false>(options?: Options<GetAllDataPlaneInstancesV4Data, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetAllDataPlaneInstancesV4Responses, unknown, ThrowOnError>({ url: '/v4alpha/dataplanes', ...options });
    }
}
