// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type DataPlaneInstanceSchemaV3 = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    /**
     * @deprecated
     */
    allowedDestTypes: Array<string>;
    allowedSourceTypes: Array<string>;
    lastActive?: number;
    state?: string;
    stateTimestamp?: number;
    /**
     * @deprecated
     */
    turnCount?: number;
    url: string;
};

export type DataPlaneInstanceSchemaV4 = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    allowedSourceTypes: Array<string>;
    lastActive?: number;
    state?: string;
    stateTimestamp?: number;
    url: string;
};

export type JsonArray = Array<JsonValue>;

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type GetAllDataPlaneInstancesV3Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v3/dataplanes';
};

export type GetAllDataPlaneInstancesV3Responses = {
    /**
     * A (potentially empty) list of currently registered data plane instances
     */
    200: Array<DataPlaneInstanceSchemaV3>;
};

export type GetAllDataPlaneInstancesV3Response = GetAllDataPlaneInstancesV3Responses[keyof GetAllDataPlaneInstancesV3Responses];

export type GetAllDataPlaneInstancesV4Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v4alpha/dataplanes';
};

export type GetAllDataPlaneInstancesV4Responses = {
    /**
     * A (potentially empty) list of currently registered data plane instances
     */
    200: Array<DataPlaneInstanceSchemaV4>;
};

export type GetAllDataPlaneInstancesV4Response = GetAllDataPlaneInstancesV4Responses[keyof GetAllDataPlaneInstancesV4Responses];
