// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { RequestProtocolVersionV4AlphaData, RequestProtocolVersionV4AlphaResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ProtocolVersionV4AlphaService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ProtocolVersionV4AlphaService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<ProtocolVersionV4AlphaService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ProtocolVersionV4AlphaService.__registry.set(this, args?.key);
    }
    
    public requestProtocolVersionV4Alpha<ThrowOnError extends boolean = false>(options?: Options<RequestProtocolVersionV4AlphaData, ThrowOnError>) {
        return (options?.client ?? this.client).post<RequestProtocolVersionV4AlphaResponses, unknown, ThrowOnError>({
            url: '/v4alpha/protocol-versions/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
