// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type CatalogRequest = {
    '@context': {
        [key: string]: unknown;
    };
    '@type'?: string;
    counterPartyAddress: string;
    counterPartyId: string;
    protocol: string;
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

/**
 * Protocol Version
 */
export type ProtocolVersion = {
    [key: string]: unknown;
};

export type RequestProtocolVersionV4AlphaData = {
    body?: CatalogRequest;
    path?: never;
    query?: never;
    url: '/v4alpha/protocol-versions/request';
};

export type RequestProtocolVersionV4AlphaResponses = {
    /**
     * Gets supported protocol versions of a single connector
     */
    default: ProtocolVersion;
};

export type RequestProtocolVersionV4AlphaResponse = RequestProtocolVersionV4AlphaResponses[keyof RequestProtocolVersionV4AlphaResponses];
