// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CheckHealthData, CheckHealthResponses, GetLivenessData, GetLivenessResponses, GetReadinessData, GetReadinessResponses, GetStartupData, GetStartupResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ApplicationObservabilityService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ApplicationObservabilityService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<ApplicationObservabilityService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ApplicationObservabilityService.__registry.set(this, args?.key);
    }
    
    /**
     * Performs a liveness probe to determine whether the runtime is working properly.
     */
    public checkHealth<ThrowOnError extends boolean = false>(options?: Options<CheckHealthData, ThrowOnError>) {
        return (options?.client ?? this.client).get<CheckHealthResponses, unknown, ThrowOnError>({ url: '/check/health', ...options });
    }
    
    /**
     * Performs a liveness probe to determine whether the runtime is working properly.
     */
    public getLiveness<ThrowOnError extends boolean = false>(options?: Options<GetLivenessData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetLivenessResponses, unknown, ThrowOnError>({ url: '/check/liveness', ...options });
    }
    
    /**
     * Performs a readiness probe to determine whether the runtime is able to accept requests.
     */
    public getReadiness<ThrowOnError extends boolean = false>(options?: Options<GetReadinessData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetReadinessResponses, unknown, ThrowOnError>({ url: '/check/readiness', ...options });
    }
    
    /**
     * Performs a startup probe to determine whether the runtime has completed startup.
     */
    public getStartup<ThrowOnError extends boolean = false>(options?: Options<GetStartupData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetStartupResponses, unknown, ThrowOnError>({ url: '/check/startup', ...options });
    }
}
