// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type Failure = {
    failureDetail?: string;
    messages?: Array<string>;
};

export type HealthCheckResult = {
    component?: string;
    failure?: Failure;
    isHealthy?: boolean;
};

export type HealthStatus = {
    componentResults?: Array<HealthCheckResult>;
    isSystemHealthy?: boolean;
};

export type CheckHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/check/health';
};

export type CheckHealthResponses = {
    /**
     * The runtime is working properly.
     */
    200: HealthStatus;
};

export type CheckHealthResponse = CheckHealthResponses[keyof CheckHealthResponses];

export type GetLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/check/liveness';
};

export type GetLivenessResponses = {
    /**
     * The runtime is working properly.
     */
    200: HealthStatus;
};

export type GetLivenessResponse = GetLivenessResponses[keyof GetLivenessResponses];

export type GetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/check/readiness';
};

export type GetReadinessResponses = {
    /**
     * The runtime is able to accept requests.
     */
    200: HealthStatus;
};

export type GetReadinessResponse = GetReadinessResponses[keyof GetReadinessResponses];

export type GetStartupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/check/startup';
};

export type GetStartupResponses = {
    /**
     * The runtime has completed startup.
     */
    200: HealthStatus;
};

export type GetStartupResponse = GetStartupResponses[keyof GetStartupResponses];
