// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateContractDefinitionV3Data, CreateContractDefinitionV3Errors, CreateContractDefinitionV3Responses, DeleteContractDefinitionV3Data, DeleteContractDefinitionV3Errors, DeleteContractDefinitionV3Responses, GetContractDefinitionV3Data, GetContractDefinitionV3Errors, GetContractDefinitionV3Responses, QueryContractDefinitionsV3Data, QueryContractDefinitionsV3Errors, QueryContractDefinitionsV3Responses, UpdateContractDefinitionV3Data, UpdateContractDefinitionV3Errors, UpdateContractDefinitionV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ContractDefinitionV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ContractDefinitionV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<ContractDefinitionV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ContractDefinitionV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Creates a new contract definition
     */
    public createContractDefinitionV3<ThrowOnError extends boolean = false>(options?: Options<CreateContractDefinitionV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<CreateContractDefinitionV3Responses, CreateContractDefinitionV3Errors, ThrowOnError>({
            url: '/v3/contractdefinitions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Updated a contract definition with the given ID. The supplied JSON structure must be a valid JSON-LD object
     */
    public updateContractDefinitionV3<ThrowOnError extends boolean = false>(options?: Options<UpdateContractDefinitionV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).put<UpdateContractDefinitionV3Responses, UpdateContractDefinitionV3Errors, ThrowOnError>({
            url: '/v3/contractdefinitions',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Returns all contract definitions according to a query
     */
    public queryContractDefinitionsV3<ThrowOnError extends boolean = false>(options?: Options<QueryContractDefinitionsV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryContractDefinitionsV3Responses, QueryContractDefinitionsV3Errors, ThrowOnError>({
            url: '/v3/contractdefinitions/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Removes a contract definition with the given ID if possible. DANGER ZONE: Note that deleting contract definitions can have unexpected results, especially for contract offers that have been sent out or ongoing or contract negotiations.
     */
    public deleteContractDefinitionV3<ThrowOnError extends boolean = false>(options: Options<DeleteContractDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteContractDefinitionV3Responses, DeleteContractDefinitionV3Errors, ThrowOnError>({ url: '/v3/contractdefinitions/{id}', ...options });
    }
    
    /**
     * Gets an contract definition with the given ID
     */
    public getContractDefinitionV3<ThrowOnError extends boolean = false>(options: Options<GetContractDefinitionV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetContractDefinitionV3Responses, GetContractDefinitionV3Errors, ThrowOnError>({ url: '/v3/contractdefinitions/{id}', ...options });
    }
}
