// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type ContractDefinitionInput = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    accessPolicyId: string;
    assetsSelector: Array<Criterion>;
    contractPolicyId: string;
};

export type ContractDefinitionOutput = {
    '@id'?: string;
    '@type'?: string;
    accessPolicyId?: string;
    assetsSelector?: Array<Criterion>;
    contractPolicyId?: string;
    createdAt?: number;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type CreateContractDefinitionV3Data = {
    body?: ContractDefinitionInput;
    path?: never;
    query?: never;
    url: '/v3/contractdefinitions';
};

export type CreateContractDefinitionV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Could not create contract definition, because a contract definition with that ID already exists
     */
    409: Array<ApiErrorDetail>;
};

export type CreateContractDefinitionV3Error = CreateContractDefinitionV3Errors[keyof CreateContractDefinitionV3Errors];

export type CreateContractDefinitionV3Responses = {
    /**
     * contract definition was created successfully. Returns the Contract Definition Id and created timestamp
     */
    200: IdResponse;
};

export type CreateContractDefinitionV3Response = CreateContractDefinitionV3Responses[keyof CreateContractDefinitionV3Responses];

export type UpdateContractDefinitionV3Data = {
    body?: ContractDefinitionInput;
    path?: never;
    query?: never;
    url: '/v3/contractdefinitions';
};

export type UpdateContractDefinitionV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A contract definition with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type UpdateContractDefinitionV3Error = UpdateContractDefinitionV3Errors[keyof UpdateContractDefinitionV3Errors];

export type UpdateContractDefinitionV3Responses = {
    /**
     * Contract definition was updated successfully
     */
    204: void;
};

export type UpdateContractDefinitionV3Response = UpdateContractDefinitionV3Responses[keyof UpdateContractDefinitionV3Responses];

export type QueryContractDefinitionsV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/contractdefinitions/request';
};

export type QueryContractDefinitionsV3Errors = {
    /**
     * Request was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryContractDefinitionsV3Error = QueryContractDefinitionsV3Errors[keyof QueryContractDefinitionsV3Errors];

export type QueryContractDefinitionsV3Responses = {
    /**
     * The contract definitions matching the query
     */
    200: Array<ContractDefinitionOutput>;
};

export type QueryContractDefinitionsV3Response = QueryContractDefinitionsV3Responses[keyof QueryContractDefinitionsV3Responses];

export type DeleteContractDefinitionV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractdefinitions/{id}';
};

export type DeleteContractDefinitionV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A contract definition with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type DeleteContractDefinitionV3Error = DeleteContractDefinitionV3Errors[keyof DeleteContractDefinitionV3Errors];

export type DeleteContractDefinitionV3Responses = {
    /**
     * Contract definition was deleted successfully
     */
    204: void;
};

export type DeleteContractDefinitionV3Response = DeleteContractDefinitionV3Responses[keyof DeleteContractDefinitionV3Responses];

export type GetContractDefinitionV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractdefinitions/{id}';
};

export type GetContractDefinitionV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract agreement with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetContractDefinitionV3Error = GetContractDefinitionV3Errors[keyof GetContractDefinitionV3Errors];

export type GetContractDefinitionV3Responses = {
    /**
     * The contract definition
     */
    200: ContractDefinitionOutput;
};

export type GetContractDefinitionV3Response = GetContractDefinitionV3Responses[keyof GetContractDefinitionV3Responses];
