// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type InitialContractOfferData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/2025-1/negotiations/offers';
};

export type InitialContractOfferResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type InitialContractRequestData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/2025-1/negotiations/request';
};

export type InitialContractRequestResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetNegotiationData = {
    body?: never;
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}';
};

export type GetNegotiationResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type CreateAgreementData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/agreement';
};

export type CreateAgreementResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type VerifyAgreementData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/agreement/verification';
};

export type VerifyAgreementResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type CreateEventData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/events';
};

export type CreateEventResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ProviderOfferData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/offers';
};

export type ProviderOfferResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ContractRequestData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/request';
};

export type ContractRequestResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type TerminateNegotiationData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/negotiations/{id}/termination';
};

export type TerminateNegotiationResponses = {
    /**
     * default response
     */
    default: unknown;
};
