// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type GetProtocolVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/.well-known/dspace-version';
};

export type GetProtocolVersionsResponses = {
    /**
     * default response
     */
    default: unknown;
};
