// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateAssetV3Data, CreateAssetV3Errors, CreateAssetV3Responses, GetAssetV3Data, GetAssetV3Errors, GetAssetV3Responses, RemoveAssetV3Data, RemoveAssetV3Errors, RemoveAssetV3Responses, RequestAssetsV3Data, RequestAssetsV3Errors, RequestAssetsV3Responses, UpdateAssetV3Data, UpdateAssetV3Errors, UpdateAssetV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new AssetV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class AssetV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<AssetV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        AssetV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Creates a new asset together with a data address
     */
    public createAssetV3<ThrowOnError extends boolean = false>(options?: Options<CreateAssetV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<CreateAssetV3Responses, CreateAssetV3Errors, ThrowOnError>({
            url: '/v3/assets',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Updates an asset with the given ID if it exists. If the asset is not found, no further action is taken. DANGER ZONE: Note that updating assets can have unexpected results, especially for contract offers that have been sent out or are ongoing in contract negotiations.
     */
    public updateAssetV3<ThrowOnError extends boolean = false>(options?: Options<UpdateAssetV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).put<UpdateAssetV3Responses, UpdateAssetV3Errors, ThrowOnError>({
            url: '/v3/assets',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Request all assets according to a particular query
     */
    public requestAssetsV3<ThrowOnError extends boolean = false>(options?: Options<RequestAssetsV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<RequestAssetsV3Responses, RequestAssetsV3Errors, ThrowOnError>({
            url: '/v3/assets/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Removes an asset with the given ID if possible. Deleting an asset is only possible if that asset is not yet referenced by a contract agreement, in which case an error is returned. DANGER ZONE: Note that deleting assets can have unexpected results, especially for contract offers that have been sent out or ongoing or contract negotiations.
     */
    public removeAssetV3<ThrowOnError extends boolean = false>(options: Options<RemoveAssetV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<RemoveAssetV3Responses, RemoveAssetV3Errors, ThrowOnError>({ url: '/v3/assets/{id}', ...options });
    }
    
    /**
     * Gets an asset with the given ID
     */
    public getAssetV3<ThrowOnError extends boolean = false>(options: Options<GetAssetV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetAssetV3Responses, GetAssetV3Errors, ThrowOnError>({ url: '/v3/assets/{id}', ...options });
    }
}
