// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type AssetInput = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    dataAddress: DataAddress;
    privateProperties?: Properties;
    properties: Properties;
};

export type AssetOutput = {
    '@id'?: string;
    '@type'?: string;
    createdAt?: number;
    dataAddress?: DataAddress;
    privateProperties?: Properties;
    properties?: Properties;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type DataAddress = {
    '@type'?: string;
    type?: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type Properties = {
    [key: string]: unknown;
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type CreateAssetV3Data = {
    body?: AssetInput;
    path?: never;
    query?: never;
    url: '/v3/assets';
};

export type CreateAssetV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Could not create asset, because an asset with that ID already exists
     */
    409: Array<ApiErrorDetail>;
};

export type CreateAssetV3Error = CreateAssetV3Errors[keyof CreateAssetV3Errors];

export type CreateAssetV3Responses = {
    /**
     * Asset was created successfully. Returns the asset Id and created timestamp
     */
    200: IdResponse;
};

export type CreateAssetV3Response = CreateAssetV3Responses[keyof CreateAssetV3Responses];

export type UpdateAssetV3Data = {
    body?: AssetInput;
    path?: never;
    query?: never;
    url: '/v3/assets';
};

export type UpdateAssetV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * Asset could not be updated, because it does not exist.
     */
    404: unknown;
};

export type UpdateAssetV3Error = UpdateAssetV3Errors[keyof UpdateAssetV3Errors];

export type UpdateAssetV3Responses = {
    /**
     * Asset was updated successfully
     */
    204: void;
};

export type UpdateAssetV3Response = UpdateAssetV3Responses[keyof UpdateAssetV3Responses];

export type RequestAssetsV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/assets/request';
};

export type RequestAssetsV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type RequestAssetsV3Error = RequestAssetsV3Errors[keyof RequestAssetsV3Errors];

export type RequestAssetsV3Responses = {
    /**
     * The assets matching the query
     */
    200: Array<AssetOutput>;
};

export type RequestAssetsV3Response = RequestAssetsV3Responses[keyof RequestAssetsV3Responses];

export type RemoveAssetV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/assets/{id}';
};

export type RemoveAssetV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An asset with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
    /**
     * The asset cannot be deleted, because it is referenced by a contract agreement
     */
    409: Array<ApiErrorDetail>;
};

export type RemoveAssetV3Error = RemoveAssetV3Errors[keyof RemoveAssetV3Errors];

export type RemoveAssetV3Responses = {
    /**
     * Asset was deleted successfully
     */
    204: void;
};

export type RemoveAssetV3Response = RemoveAssetV3Responses[keyof RemoveAssetV3Responses];

export type GetAssetV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/assets/{id}';
};

export type GetAssetV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An asset with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetAssetV3Error = GetAssetV3Errors[keyof GetAssetV3Errors];

export type GetAssetV3Responses = {
    /**
     * The asset
     */
    200: AssetOutput;
};

export type GetAssetV3Response = GetAssetV3Responses[keyof GetAssetV3Responses];
