// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CallDeprovisionWebhookData, CallDeprovisionWebhookResponses, CallProvisionWebhookData, CallProvisionWebhookResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new HttpProvisionerWebhookService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class HttpProvisionerWebhookService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<HttpProvisionerWebhookService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        HttpProvisionerWebhookService.__registry.set(this, args?.key);
    }
    
    /**
     * @deprecated
     */
    public callDeprovisionWebhook<ThrowOnError extends boolean = false>(options: Options<CallDeprovisionWebhookData, ThrowOnError>) {
        return (options.client ?? this.client).post<CallDeprovisionWebhookResponses, unknown, ThrowOnError>({
            url: '/callback/{processId}/deprovision',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * @deprecated
     */
    public callProvisionWebhook<ThrowOnError extends boolean = false>(options: Options<CallProvisionWebhookData, ThrowOnError>) {
        return (options.client ?? this.client).post<CallProvisionWebhookResponses, unknown, ThrowOnError>({
            url: '/callback/{processId}/provision',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
