// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type DataAddress = {
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type DeprovisionedResource = {
    error?: boolean;
    errorMessage?: string;
    inProcess?: boolean;
    provisionedResourceId?: string;
};

export type ProvisionerWebhookRequest = {
    apiKeyJwt?: string;
    assetId?: string;
    contentDataAddress?: DataAddress;
    hasToken?: boolean;
    resourceDefinitionId?: string;
    resourceName?: string;
};

export type CallDeprovisionWebhookData = {
    body?: DeprovisionedResource;
    path: {
        processId: string;
    };
    query?: never;
    url: '/callback/{processId}/deprovision';
};

export type CallDeprovisionWebhookResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type CallProvisionWebhookData = {
    body?: ProvisionerWebhookRequest;
    path: {
        processId: string;
    };
    query?: never;
    url: '/callback/{processId}/provision';
};

export type CallProvisionWebhookResponses = {
    /**
     * default response
     */
    default: unknown;
};
