// This file is auto-generated by @hey-api/openapi-ts

export { type Options, SecretV3Service } from './sdk.gen.js';
export type { ApiErrorDetail, ClientOptions, CreateSecretV3Data, CreateSecretV3Error, CreateSecretV3Errors, CreateSecretV3Response, CreateSecretV3Responses, GetSecretV3Data, GetSecretV3Error, GetSecretV3Errors, GetSecretV3Response, GetSecretV3Responses, IdResponse, JsonObject, JsonValue, RemoveSecretV3Data, RemoveSecretV3Error, RemoveSecretV3Errors, RemoveSecretV3Response, RemoveSecretV3Responses, SecretInput, SecretOutput, UpdateSecretV3Data, UpdateSecretV3Error, UpdateSecretV3Errors, UpdateSecretV3Response, UpdateSecretV3Responses } from './types.gen.js';
