// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateSecretV3Data, CreateSecretV3Errors, CreateSecretV3Responses, GetSecretV3Data, GetSecretV3Errors, GetSecretV3Responses, RemoveSecretV3Data, RemoveSecretV3Errors, RemoveSecretV3Responses, UpdateSecretV3Data, UpdateSecretV3Errors, UpdateSecretV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new SecretV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class SecretV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<SecretV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        SecretV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Creates a new secret.
     */
    public createSecretV3<ThrowOnError extends boolean = false>(options?: Options<CreateSecretV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<CreateSecretV3Responses, CreateSecretV3Errors, ThrowOnError>({
            url: '/v3/secrets',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Updates a secret with the given ID if it exists. If the secret is not found, no further action is taken.
     */
    public updateSecretV3<ThrowOnError extends boolean = false>(options?: Options<UpdateSecretV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).put<UpdateSecretV3Responses, UpdateSecretV3Errors, ThrowOnError>({
            url: '/v3/secrets',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Removes a secret with the given ID if possible.
     */
    public removeSecretV3<ThrowOnError extends boolean = false>(options: Options<RemoveSecretV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<RemoveSecretV3Responses, RemoveSecretV3Errors, ThrowOnError>({ url: '/v3/secrets/{id}', ...options });
    }
    
    /**
     * Gets a secret with the given ID
     */
    public getSecretV3<ThrowOnError extends boolean = false>(options: Options<GetSecretV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetSecretV3Responses, GetSecretV3Errors, ThrowOnError>({ url: '/v3/secrets/{id}', ...options });
    }
}
