// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type SecretInput = {
    '@context': {
        [key: string]: unknown;
    };
    '@id'?: string;
    '@type'?: string;
    value: string;
};

export type SecretOutput = {
    '@id'?: string;
    '@type'?: string;
    value: string;
};

export type CreateSecretV3Data = {
    body?: SecretInput;
    path?: never;
    query?: never;
    url: '/v3/secrets';
};

export type CreateSecretV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * Could not create secret, because a secret with that ID already exists
     */
    409: Array<ApiErrorDetail>;
};

export type CreateSecretV3Error = CreateSecretV3Errors[keyof CreateSecretV3Errors];

export type CreateSecretV3Responses = {
    /**
     * Secret was created successfully. Returns the secret Id and created timestamp
     */
    200: IdResponse;
};

export type CreateSecretV3Response = CreateSecretV3Responses[keyof CreateSecretV3Responses];

export type UpdateSecretV3Data = {
    body?: SecretInput;
    path?: never;
    query?: never;
    url: '/v3/secrets';
};

export type UpdateSecretV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * Secret could not be updated, because it does not exist.
     */
    404: unknown;
};

export type UpdateSecretV3Error = UpdateSecretV3Errors[keyof UpdateSecretV3Errors];

export type UpdateSecretV3Responses = {
    /**
     * Secret was updated successfully
     */
    204: void;
};

export type UpdateSecretV3Response = UpdateSecretV3Responses[keyof UpdateSecretV3Responses];

export type RemoveSecretV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/secrets/{id}';
};

export type RemoveSecretV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A secret with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type RemoveSecretV3Error = RemoveSecretV3Errors[keyof RemoveSecretV3Errors];

export type RemoveSecretV3Responses = {
    /**
     * Secret was deleted successfully
     */
    204: void;
};

export type RemoveSecretV3Response = RemoveSecretV3Responses[keyof RemoveSecretV3Responses];

export type GetSecretV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/secrets/{id}';
};

export type GetSecretV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A secret with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetSecretV3Error = GetSecretV3Errors[keyof GetSecretV3Errors];

export type GetSecretV3Responses = {
    /**
     * The secret
     */
    200: SecretOutput;
};

export type GetSecretV3Response = GetSecretV3Responses[keyof GetSecretV3Responses];
