// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type GetDatasetData = {
    body?: never;
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2024/1/catalog/datasets/{id}';
};

export type GetDatasetResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type RequestCatalogData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path?: never;
    query?: {
        continuationToken?: string;
    };
    url: '/2024/1/catalog/request';
};

export type RequestCatalogResponses = {
    /**
     * default response
     */
    default: unknown;
};
