// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeleteData, DeleteErrors, GetData, GetErrors, HeadData, HeadErrors, PatchData, PatchErrors, PostData, PostErrors, PutData, PutErrors } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DataPlanePublicApiService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DataPlanePublicApiService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DataPlanePublicApiService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DataPlanePublicApiService.__registry.set(this, args?.key);
    }
    
    /**
     * Send `DELETE` data query to the Data Plane.
     *
     * @deprecated
     */
    public delete<ThrowOnError extends boolean = false>(options?: Options<DeleteData, ThrowOnError>) {
        return (options?.client ?? this.client).delete<unknown, DeleteErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
    
    /**
     * Send `GET` data query to the Data Plane.
     *
     * @deprecated
     */
    public get<ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) {
        return (options?.client ?? this.client).get<unknown, GetErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
    
    /**
     * Send `HEAD` data query to the Data Plane.
     *
     * @deprecated
     */
    public head<ThrowOnError extends boolean = false>(options?: Options<HeadData, ThrowOnError>) {
        return (options?.client ?? this.client).head<unknown, HeadErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
    
    /**
     * Send `PATCH` data query to the Data Plane.
     *
     * @deprecated
     */
    public patch<ThrowOnError extends boolean = false>(options?: Options<PatchData, ThrowOnError>) {
        return (options?.client ?? this.client).patch<unknown, PatchErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
    
    /**
     * Send `POST` data query to the Data Plane.
     *
     * @deprecated
     */
    public post<ThrowOnError extends boolean = false>(options?: Options<PostData, ThrowOnError>) {
        return (options?.client ?? this.client).post<unknown, PostErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
    
    /**
     * Send `PUT` data query to the Data Plane.
     *
     * @deprecated
     */
    public put<ThrowOnError extends boolean = false>(options?: Options<PutData, ThrowOnError>) {
        return (options?.client ?? this.client).put<unknown, PutErrors, ThrowOnError>({ url: '/{any}', ...options });
    }
}
