// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type DeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type DeleteErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type GetErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};

export type HeadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type HeadErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};

export type PatchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type PatchErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};

export type PostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type PostErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};

export type PutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/{any}';
};

export type PutErrors = {
    /**
     * Missing access token
     */
    400: unknown;
    /**
     * Access token is expired or invalid
     */
    403: unknown;
    /**
     * Failed to transfer data
     */
    500: unknown;
};
