// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetTransferProcessData, GetTransferProcessResponses, InitiateTransferProcessData, InitiateTransferProcessResponses, TransferProcessCompletionData, TransferProcessCompletionResponses, TransferProcessStartData, TransferProcessStartResponses, TransferProcessSuspensionData, TransferProcessSuspensionResponses, TransferProcessTerminationData, TransferProcessTerminationResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new DefaultService()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class DefaultService extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<DefaultService>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        DefaultService.__registry.set(this, args?.key);
    }
    
    public initiateTransferProcess<ThrowOnError extends boolean = false>(options?: Options<InitiateTransferProcessData, ThrowOnError>) {
        return (options?.client ?? this.client).post<InitiateTransferProcessResponses, unknown, ThrowOnError>({
            url: '/2025-1/transfers/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public getTransferProcess<ThrowOnError extends boolean = false>(options: Options<GetTransferProcessData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetTransferProcessResponses, unknown, ThrowOnError>({ url: '/2025-1/transfers/{id}', ...options });
    }
    
    public transferProcessCompletion<ThrowOnError extends boolean = false>(options: Options<TransferProcessCompletionData, ThrowOnError>) {
        return (options.client ?? this.client).post<TransferProcessCompletionResponses, unknown, ThrowOnError>({
            url: '/2025-1/transfers/{id}/completion',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public transferProcessStart<ThrowOnError extends boolean = false>(options: Options<TransferProcessStartData, ThrowOnError>) {
        return (options.client ?? this.client).post<TransferProcessStartResponses, unknown, ThrowOnError>({
            url: '/2025-1/transfers/{id}/start',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public transferProcessSuspension<ThrowOnError extends boolean = false>(options: Options<TransferProcessSuspensionData, ThrowOnError>) {
        return (options.client ?? this.client).post<TransferProcessSuspensionResponses, unknown, ThrowOnError>({
            url: '/2025-1/transfers/{id}/suspension',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public transferProcessTermination<ThrowOnError extends boolean = false>(options: Options<TransferProcessTerminationData, ThrowOnError>) {
        return (options.client ?? this.client).post<TransferProcessTerminationResponses, unknown, ThrowOnError>({
            url: '/2025-1/transfers/{id}/termination',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
