// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type InitiateTransferProcessData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/2025-1/transfers/request';
};

export type InitiateTransferProcessResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type GetTransferProcessData = {
    body?: never;
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/transfers/{id}';
};

export type GetTransferProcessResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type TransferProcessCompletionData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/transfers/{id}/completion';
};

export type TransferProcessCompletionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type TransferProcessStartData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/transfers/{id}/start';
};

export type TransferProcessStartResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type TransferProcessSuspensionData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/transfers/{id}/suspension';
};

export type TransferProcessSuspensionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type TransferProcessTerminationData = {
    body?: {
        empty?: boolean;
        valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
        [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
    };
    headers?: {
        Authorization?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/2025-1/transfers/{id}/termination';
};

export type TransferProcessTerminationResponses = {
    /**
     * default response
     */
    default: unknown;
};
