// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { DeleteNegotiationV3Data, DeleteNegotiationV3Errors, DeleteNegotiationV3Responses, GetAgreementForNegotiationV3Data, GetAgreementForNegotiationV3Errors, GetAgreementForNegotiationV3Responses, GetNegotiationStateV3Data, GetNegotiationStateV3Errors, GetNegotiationStateV3Responses, GetNegotiationV3Data, GetNegotiationV3Errors, GetNegotiationV3Responses, InitiateContractNegotiationV3Data, InitiateContractNegotiationV3Errors, InitiateContractNegotiationV3Responses, QueryNegotiationsV3Data, QueryNegotiationsV3Errors, QueryNegotiationsV3Responses, TerminateNegotiationV3Data, TerminateNegotiationV3Errors, TerminateNegotiationV3Responses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ContractNegotiationV3Service()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ContractNegotiationV3Service extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<ContractNegotiationV3Service>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ContractNegotiationV3Service.__registry.set(this, args?.key);
    }
    
    /**
     * Initiates a contract negotiation for a given offer and with the given counter part. Please note that successfully invoking this endpoint only means that the negotiation was initiated. Clients must poll the /{id}/state endpoint to track the state
     */
    public initiateContractNegotiationV3<ThrowOnError extends boolean = false>(options?: Options<InitiateContractNegotiationV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<InitiateContractNegotiationV3Responses, InitiateContractNegotiationV3Errors, ThrowOnError>({
            url: '/v3/contractnegotiations',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Returns all contract negotiations according to a query
     */
    public queryNegotiationsV3<ThrowOnError extends boolean = false>(options?: Options<QueryNegotiationsV3Data, ThrowOnError>) {
        return (options?.client ?? this.client).post<QueryNegotiationsV3Responses, QueryNegotiationsV3Errors, ThrowOnError>({
            url: '/v3/contractnegotiations/request',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Deletes the contract negotiation with the given ID. Only terminated negotiations without agreement will be deleted
     */
    public deleteNegotiationV3<ThrowOnError extends boolean = false>(options: Options<DeleteNegotiationV3Data, ThrowOnError>) {
        return (options.client ?? this.client).delete<DeleteNegotiationV3Responses, DeleteNegotiationV3Errors, ThrowOnError>({ url: '/v3/contractnegotiations/{id}', ...options });
    }
    
    /**
     * Gets a contract negotiation with the given ID
     */
    public getNegotiationV3<ThrowOnError extends boolean = false>(options: Options<GetNegotiationV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetNegotiationV3Responses, GetNegotiationV3Errors, ThrowOnError>({ url: '/v3/contractnegotiations/{id}', ...options });
    }
    
    /**
     * Gets a contract agreement for a contract negotiation with the given ID
     */
    public getAgreementForNegotiationV3<ThrowOnError extends boolean = false>(options: Options<GetAgreementForNegotiationV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetAgreementForNegotiationV3Responses, GetAgreementForNegotiationV3Errors, ThrowOnError>({ url: '/v3/contractnegotiations/{id}/agreement', ...options });
    }
    
    /**
     * Gets the state of a contract negotiation with the given ID
     */
    public getNegotiationStateV3<ThrowOnError extends boolean = false>(options: Options<GetNegotiationStateV3Data, ThrowOnError>) {
        return (options.client ?? this.client).get<GetNegotiationStateV3Responses, GetNegotiationStateV3Errors, ThrowOnError>({ url: '/v3/contractnegotiations/{id}/state', ...options });
    }
    
    /**
     * Terminates the contract negotiation.
     */
    public terminateNegotiationV3<ThrowOnError extends boolean = false>(options: Options<TerminateNegotiationV3Data, ThrowOnError>) {
        return (options.client ?? this.client).post<TerminateNegotiationV3Responses, TerminateNegotiationV3Errors, ThrowOnError>({
            url: '/v3/contractnegotiations/{id}/terminate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
