// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type ApiErrorDetail = {
    invalidValue?: string;
    message?: string;
    path?: string;
    type?: string;
};

export type CallbackAddress = {
    '@type'?: string;
    authCodeId?: string;
    authKey?: string;
    events?: Array<string>;
    transactional?: boolean;
    uri?: string;
};

export type ContractAgreement = {
    '@id'?: string;
    '@type'?: string;
    assetId?: string;
    consumerId?: string;
    contractSigningDate?: number;
    policy?: Policy;
    providerId?: string;
};

export type ContractNegotiation = {
    '@id'?: string;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractAgreementId?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    errorDetail?: string;
    protocol?: string;
    state?: string;
    type?: 'CONSUMER' | 'PROVIDER';
};

export type ContractRequest = {
    '@context': {
        [key: string]: unknown;
    };
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    counterPartyAddress: string;
    policy: Offer;
    protocol: string;
};

export type Criterion = {
    '@type'?: string;
    operandLeft: {
        [key: string]: unknown;
    };
    operandRight: {
        [key: string]: unknown;
    };
    operator: string;
};

export type IdResponse = {
    '@id'?: string;
    createdAt?: number;
};

export type JsonArray = Array<JsonValue>;

export type JsonObject = {
    empty?: boolean;
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    [key: string]: JsonValue | boolean | 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL' | undefined;
};

export type JsonValue = {
    valueType?: 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
};

export type NegotiationState = {
    state?: string;
};

/**
 * ODRL offer
 */
export type Offer = {
    '@id': string;
    '@type'?: string;
    assigner: string;
    target: string;
};

/**
 * ODRL policy
 */
export type Policy = {
    [key: string]: unknown;
};

export type QuerySpec = {
    '@type'?: string;
    filterExpression?: Array<Criterion>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: 'ASC' | 'DESC';
};

export type TerminateNegotiationSchema = {
    '@id'?: string;
    '@type'?: string;
    reason?: string;
};

export type InitiateContractNegotiationV3Data = {
    body?: ContractRequest;
    path?: never;
    query?: never;
    url: '/v3/contractnegotiations';
};

export type InitiateContractNegotiationV3Errors = {
    /**
     * Request body was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type InitiateContractNegotiationV3Error = InitiateContractNegotiationV3Errors[keyof InitiateContractNegotiationV3Errors];

export type InitiateContractNegotiationV3Responses = {
    /**
     * The negotiation was successfully initiated. Returns the contract negotiation ID and created timestamp
     */
    200: IdResponse;
};

export type InitiateContractNegotiationV3Response = InitiateContractNegotiationV3Responses[keyof InitiateContractNegotiationV3Responses];

export type QueryNegotiationsV3Data = {
    body?: QuerySpec;
    path?: never;
    query?: never;
    url: '/v3/contractnegotiations/request';
};

export type QueryNegotiationsV3Errors = {
    /**
     * Request was malformed
     */
    400: Array<ApiErrorDetail>;
};

export type QueryNegotiationsV3Error = QueryNegotiationsV3Errors[keyof QueryNegotiationsV3Errors];

export type QueryNegotiationsV3Responses = {
    /**
     * The contract negotiations that match the query
     */
    200: Array<ContractNegotiation>;
};

export type QueryNegotiationsV3Response = QueryNegotiationsV3Responses[keyof QueryNegotiationsV3Responses];

export type DeleteNegotiationV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractnegotiations/{id}';
};

export type DeleteNegotiationV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * A contract negotiation with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
    /**
     * The given contract negotiation cannot be deleted due to a wrong state or has existing contract agreement
     */
    409: Array<ApiErrorDetail>;
};

export type DeleteNegotiationV3Error = DeleteNegotiationV3Errors[keyof DeleteNegotiationV3Errors];

export type DeleteNegotiationV3Responses = {
    /**
     * ContractNegotiation is deleted
     */
    204: void;
};

export type DeleteNegotiationV3Response = DeleteNegotiationV3Responses[keyof DeleteNegotiationV3Responses];

export type GetNegotiationV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractnegotiations/{id}';
};

export type GetNegotiationV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract negotiation with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetNegotiationV3Error = GetNegotiationV3Errors[keyof GetNegotiationV3Errors];

export type GetNegotiationV3Responses = {
    /**
     * The contract negotiation
     */
    200: ContractNegotiation;
};

export type GetNegotiationV3Response = GetNegotiationV3Responses[keyof GetNegotiationV3Responses];

export type GetAgreementForNegotiationV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractnegotiations/{id}/agreement';
};

export type GetAgreementForNegotiationV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract negotiation with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetAgreementForNegotiationV3Error = GetAgreementForNegotiationV3Errors[keyof GetAgreementForNegotiationV3Errors];

export type GetAgreementForNegotiationV3Responses = {
    /**
     * The contract agreement that is attached to the negotiation, or null
     */
    200: ContractAgreement;
};

export type GetAgreementForNegotiationV3Response = GetAgreementForNegotiationV3Responses[keyof GetAgreementForNegotiationV3Responses];

export type GetNegotiationStateV3Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractnegotiations/{id}/state';
};

export type GetNegotiationStateV3Errors = {
    /**
     * Request was malformed, e.g. id was null
     */
    400: Array<ApiErrorDetail>;
    /**
     * An contract negotiation with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type GetNegotiationStateV3Error = GetNegotiationStateV3Errors[keyof GetNegotiationStateV3Errors];

export type GetNegotiationStateV3Responses = {
    /**
     * The contract negotiation's state
     */
    200: NegotiationState;
};

export type GetNegotiationStateV3Response = GetNegotiationStateV3Responses[keyof GetNegotiationStateV3Responses];

export type TerminateNegotiationV3Data = {
    body?: TerminateNegotiationSchema;
    path: {
        id: string;
    };
    query?: never;
    url: '/v3/contractnegotiations/{id}/terminate';
};

export type TerminateNegotiationV3Errors = {
    /**
     * Request was malformed
     */
    400: Array<ApiErrorDetail>;
    /**
     * A contract negotiation with the given ID does not exist
     */
    404: Array<ApiErrorDetail>;
};

export type TerminateNegotiationV3Error = TerminateNegotiationV3Errors[keyof TerminateNegotiationV3Errors];

export type TerminateNegotiationV3Responses = {
    /**
     * ContractNegotiation is terminating
     */
    200: unknown;
};
