openapi: 3.0.1
info:
  version: v4
paths:
  /v3/dataplanes:
    get:
      description: Returns a list of all currently registered data plane instances
      operationId: getAllDataPlaneInstancesV3
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DataPlaneInstanceSchemaV3"
          description: A (potentially empty) list of currently registered data plane
            instances
      tags:
      - Dataplane Selector V3
  /v4alpha/dataplanes:
    get:
      description: Returns a list of all currently registered data plane instances
      operationId: getAllDataPlaneInstancesV4
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DataPlaneInstanceSchemaV4"
          description: A (potentially empty) list of currently registered data plane
            instances
      tags:
      - Dataplane Selector v4alpha
components:
  schemas:
    DataPlaneInstanceSchemaV3:
      type: object
      example:
        '@context':
          '@vocab': https://w3id.org/edc/v0.0.1/ns/
        '@id': your-dataplane-id
        url: http://somewhere.com:1234/api/v1
        allowedSourceTypes:
        - source-type1
        - source-type2
        allowedDestTypes:
        - your-dest-type
        allowedTransferTypes:
        - transfer-type
        state: AVAILABLE
        stateTimestamp: 1688465655
      properties:
        '@context':
          type: object
        '@id':
          type: string
        '@type':
          type: string
          example: https://w3id.org/edc/v0.0.1/ns/DataPlaneInstance
        allowedDestTypes:
          type: array
          deprecated: true
          items:
            type: string
            deprecated: true
          uniqueItems: true
        allowedSourceTypes:
          type: array
          items:
            type: string
          uniqueItems: true
        lastActive:
          type: integer
          format: int64
        state:
          type: string
        stateTimestamp:
          type: integer
          format: int64
        turnCount:
          type: integer
          format: int32
          deprecated: true
        url:
          type: string
          format: url
      required:
      - '@context'
      - allowedDestTypes
      - allowedSourceTypes
      - url
    DataPlaneInstanceSchemaV4:
      type: object
      example:
        '@context':
          '@vocab': https://w3id.org/edc/v0.0.1/ns/
        '@id': your-dataplane-id
        url: http://somewhere.com:1234/api/v1
        allowedSourceTypes:
        - source-type1
        - source-type2
        allowedTransferTypes:
        - transfer-type
        state: AVAILABLE
        stateTimestamp: 1688465655
      properties:
        '@context':
          type: object
        '@id':
          type: string
        '@type':
          type: string
          example: https://w3id.org/edc/v0.0.1/ns/DataPlaneInstance
        allowedSourceTypes:
          type: array
          items:
            type: string
          uniqueItems: true
        lastActive:
          type: integer
          format: int64
        state:
          type: string
        stateTimestamp:
          type: integer
          format: int64
        url:
          type: string
          format: url
      required:
      - '@context'
      - allowedSourceTypes
      - url
    JsonArray:
      type: array
      items:
        $ref: "#/components/schemas/JsonValue"
      properties:
        empty:
          type: boolean
        first:
          $ref: "#/components/schemas/JsonValue"
        last:
          $ref: "#/components/schemas/JsonValue"
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
