openapi: 3.0.1
info:
  description: "This contains the secret management API, which allows to add, remove\
    \ and update secrets in the Vault."
  title: Secret API
  version: v3
paths:
  /v3/secrets:
    post:
      description: Creates a new secret.
      operationId: createSecretV3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SecretInput"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IdResponse"
          description: Secret was created successfully. Returns the secret Id and
            created timestamp
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Request body was malformed
        "409":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Could not create secret, because a secret with that ID already\
            \ exists"
      tags:
      - Secret V3
    put:
      description: "Updates a secret with the given ID if it exists. If the secret\
        \ is not found, no further action is taken. "
      operationId: updateSecretV3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SecretInput"
      responses:
        "204":
          description: Secret was updated successfully
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request was malformed, e.g. id was null"
        "404":
          description: "Secret could not be updated, because it does not exist."
      tags:
      - Secret V3
  /v3/secrets/{id}:
    delete:
      description: Removes a secret with the given ID if possible.
      operationId: removeSecretV3
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Secret was deleted successfully
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: A secret with the given ID does not exist
      tags:
      - Secret V3
    get:
      description: Gets a secret with the given ID
      operationId: getSecretV3
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecretOutput"
          description: The secret
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: A secret with the given ID does not exist
      tags:
      - Secret V3
components:
  schemas:
    ApiErrorDetail:
      type: object
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
    IdResponse:
      type: object
      example:
        '@context':
          '@vocab': https://w3id.org/edc/v0.0.1/ns/
        '@id': id-value
        createdAt: 1688465655
      properties:
        '@id':
          type: string
        createdAt:
          type: integer
          format: int64
    JsonObject:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/JsonValue"
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    SecretInput:
      type: object
      example:
        '@context':
          '@vocab': https://w3id.org/edc/v0.0.1/ns/
        '@id': secret-id
        value: secret-value
      properties:
        '@context':
          type: object
        '@id':
          type: string
        '@type':
          type: string
          example: https://w3id.org/edc/v0.0.1/ns/Secret
        value:
          type: string
      required:
      - '@context'
      - value
    SecretOutput:
      type: object
      example:
        '@context':
          '@vocab': https://w3id.org/edc/v0.0.1/ns/
        '@id': secret-id
        '@type': https://w3id.org/edc/v0.0.1/ns/Secret
        value: secret-value
      properties:
        '@id':
          type: string
        '@type':
          type: string
          example: https://w3id.org/edc/v0.0.1/ns/Secret
        value:
          type: string
      required:
      - value
