// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://spec` | (string & {});
};

export type DataAddress = {
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type ProvisionHttpResponse = {
    dataAddress?: DataAddress;
};

export type DeprovisionData = {
    body?: never;
    path: {
        flowId: string;
        resourceId: string;
    };
    query?: never;
    url: '/{flowId}/{resourceId}/deprovision';
};

export type DeprovisionResponses = {
    /**
     * default response
     */
    default: unknown;
};

export type ProvisionData = {
    body?: ProvisionHttpResponse;
    path: {
        flowId: string;
        resourceId: string;
    };
    query?: never;
    url: '/{flowId}/{resourceId}/provision';
};

export type ProvisionResponses = {
    /**
     * default response
     */
    default: unknown;
};
